<?php
/**
 * Created by PhpStorm.
 * User: relisoft
 * Date: 1/18/18
 * Time: 10:30 AM
 */

namespace Relisoft\Geoip\DI;


use Nette\Configurator;
use Nette\DI\Compiler;
use Nette\DI\CompilerExtension;
use Relisoft\Geoip\Diagnostics\Panel;
use Relisoft\Geoip\Geoip;

class GeoipExtension extends CompilerExtension
{
    private $defaults = [
        "cache" => true,
        "debugger" => "%debugMode%"
    ];

    public function loadConfiguration()
    {
        $this->validateConfig($this->defaults);

        $builder = $this->getContainerBuilder();
        $geo = $builder->addDefinition($this->prefix("geoip"))
            ->setFactory(Geoip::class)
            ->addSetup("setCache",[$this->config["cache"]]);
        $builder->addDefinition($this->prefix("panel"))
            ->setFactory(Panel::class)
            ->setInject(false);
        $geo->addSetup($this->prefix('@panel') . '::register', ['@self']);
        parent::loadConfiguration(); // TODO: Change the autogenerated stub
    }

    /**
     * @param \Nette\Configurator $configurator
     */
    public static function register(Configurator $configurator)
    {
        $configurator->onCompile[] = function ($config, Compiler $compiler) {
            $compiler->addExtension('geoip', new GeoipExtension());
        };
    }
}